# Generated by Django 5.1.6 on 2025-03-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_time',
            field=models.DateField(),
        ),
    ]
